[package]
name    = "ndarray-linalg"
version = "0.9.1-alpha.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description   = "Linear algebra package for rust-ndarray using LAPACK"
documentation = "https://docs.rs/ndarray-linalg/"
repository    = "https://github.com/termoshtt/ndarray-linalg"
keywords      = ["ndarray", "lapack", "matrix"]
license       = "MIT"
readme        = "README.md"
categories    = ["algorithms", "science"]

[features]
default    = []
accelerate = ["lapack-src/accelerate", "blas-src/accelerate"]
intel-mkl  = ["lapack-src/intel-mkl", "blas-src/intel-mkl"]
netlib     = ["lapack-src/netlib", "blas-src/netlib", "netlib-src"]
openblas   = ["lapack-src/openblas", "blas-src/openblas", "openblas-src"]

[dependencies]
derive-new = "0.5"
lapacke = "0.1.4"
num-traits  = "0.1"
procedurals = "0.2"
rand = "0.4"

[dependencies.num-complex]
version = "0.1"
default-features = false

[dependencies.ndarray]
version = "0.11"
features = ["blas"]
default-features = false

[dependencies.blas-src]
version = "0.1"
default-features = false
optional = true

[dependencies.lapack-src]
version = "0.1"
default-features = false
optional = true

[dependencies.netlib-src]
version = "0.7.0"
features = ["static", "cblas", "lapacke", "tmg"]
default-features = false
optional = true

[dependencies.openblas-src]
version = "0.5.3"
features = ["static", "cblas", "lapacke"]
default-features = false
optional = true

# Use OpenBLAS backend for examples, tests, and benchmarks.
[dev-dependencies.blas-src]
version = "0.1"
features = ["openblas"]
